import React from "react";
import InventoryTransactionForm from "@/app/components/inventory-transaction/InventoryTransactionForm";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create New Inventory",
  description: "Generated by create next app",
};

//LOGIC TO DISPLAY CREATE INVENTORY PAGE
const CreateInventoryTransactionPage = () => {
  return (
    <main className="p-8 bg-gray-100 min-h-screen">
      <h1 className="text-2xl font-bold mb-6">Create Inventory Transaction</h1>
      <InventoryTransactionForm />
    </main>
  );
};

export default CreateInventoryTransactionPage;
