import React from "react";
import { Metadata } from "next";
import WarehouseForm from "@/app/components/warehouse/WarehouseForm";

export const metadata: Metadata = {
  title: "Create New Warehouse",
  description: "Generated by create next app",
};

//LOGIC TO DISPLAY CREATE WAREHOUSE PAGE
const CreateWarehousePage: React.FC = () => {
  return (
    <main className="p-8 bg-gray-100 min-h-screen">
      <h1 className="text-2xl font-bold mb-6">Create New Warehouse</h1>
      <WarehouseForm />
    </main>
  );
};

export default CreateWarehousePage;
