import React from "react";
import { Metadata } from "next";
import StaffAssignmentForm from "@/app/components/staff-assignment/StaffAssignmentForm";

export const metadata: Metadata = {
  title: "Add New Staff To Warehouse",
  description: "Generated by create next app",
};

//LOGIC TO DISPLAY CREATE PRODUCT PAGE
const CreateStaffAssignmentPage: React.FC = () => {
  return (
    <main className="p-8 bg-gray-100 min-h-screen">
      <h1 className="text-2xl font-bold mb-6">Add New Staff To Warehouse</h1>
      <StaffAssignmentForm />
    </main>
  );
};

export default CreateStaffAssignmentPage;
