import React from "react";
import CategoryForm from "@/app/components/category/CategoryForm";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create New Category",
  description: "Generated by create next app",
};

//LOGIC TO DISPLAY CREATE CATEGORY PAGE
const CreateCategoryPage: React.FC = () => {
  return (
    <main className="p-8 bg-gray-100 min-h-screen">
      <h1 className="text-2xl font-bold mb-6">Create New Category</h1>
      <CategoryForm />
    </main>
  );
};

export default CreateCategoryPage;
