import React from "react";
import { Metadata } from "next";
import SupplierForm from "@/app/components/supplier/SupplierForm";

export const metadata: Metadata = {
  title: "Create New Supplier",
  description: "Generated by create next app",
};

//LOGIC TO DISPLAY CREATE CATEGORY PAGE
const CreateSupplierPage: React.FC = () => {
  return (
    <main className="p-8 bg-gray-100 min-h-screen">
      <h1 className="text-2xl font-bold mb-6">Create New Supplier</h1>
      <SupplierForm />
    </main>
  );
};

export default CreateSupplierPage;
