import React from "react";
import { Metadata } from "next";
import ProductForm from "@/app/components/product/ProductForm";

export const metadata: Metadata = {
  title: "Create New Product",
  description: "Generated by create next app",
};

//LOGIC TO DISPLAY CREATE PRODUCT PAGE
const CreateProductPage: React.FC = () => {
  return (
    <main className="p-8 bg-gray-100 min-h-screen">
      <h1 className="text-2xl font-bold mb-6">Create New Product</h1>
      <ProductForm />
    </main>
  );
};

export default CreateProductPage;
